Repository flingengine/FlingEngine, pull requests merged in 2019-11, with the labels that each got.

#106 Implement MSAA
  FlingEngine/Graphics/inc/Cubemap.h
  FlingEngine/Graphics/inc/DepthBuffer.h
  FlingEngine/Graphics/inc/GraphicsHelpers.h
  FlingEngine/Graphics/inc/MultiSampler.h
  FlingEngine/Graphics/inc/PhyscialDevice.h
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/src/Cubemap.cpp
  FlingEngine/Graphics/src/DepthBuffer.cpp
  FlingEngine/Graphics/src/GraphicsHelpers.cpp
  FlingEngine/Graphics/src/MultiSampler.cpp
  FlingEngine/Graphics/src/PhyscialDevice.cpp
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Resources/inc/Image.h
  FlingEngine/Resources/src/Image.cpp
  Sandbox/Gameplay/inc/Mover.h
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: enhancement

#110 Add the ability to set the window icon on `FlingWindow`
  Assets/FlingEngineLogo.png
  Assets/Icons/Fling_Logo.png
  FlingEngine/Graphics/inc/DesktopWindow.h
  FlingEngine/Graphics/inc/FlingWindow.h
  FlingEngine/Graphics/src/DesktopWindow.cpp
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: PRI 3, enhancement

#116 Add a Free List for easy use of a pool allocator
  FlingEngine/Utils/inc/FreeList.h
  FlingEngine/Utils/src/FreeList.cpp
  FlingTests/src/UtilsTests.cpp
Labels: enhancement

#117 Initalzie the DT to 1 over 60 instead of 0
  FlingEngine/Core/src/Input/LinuxInput.cpp
  FlingEngine/Core/src/Input/WindowsInput.cpp
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Utils/inc/Timing.h
  FlingEngine/Utils/src/Timing.cpp
Labels: bug fix

#119 Point light debug fix
  FlingEngine/Graphics/src/Renderer.cpp
Labels: PRI 0, bug fix

#125 Editor
  Assets/Levels/EmptyLevel.json
  Assets/Levels/Level_1.json
  CMakeLists.txt
  FlingEngine/CMakeLists.txt
  FlingEngine/Core/inc/Serilization.h
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Editor/inc/BaseEditor.h
  FlingEngine/Editor/inc/FileBrowser.h
  FlingEngine/Editor/inc/ImFileBrowser.hpp
  FlingEngine/Editor/src/BaseEditor.cpp
  FlingEngine/Editor/src/FileBrowser.cpp
  FlingEngine/Graphics/inc/MeshRenderer.h
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Graphics/src/ShaderPrograms/ShaderProgramPbr.cpp
  FlingEngine/Platform/inc/ImGuiInputBinding.hpp
  FlingEngine/Resources/inc/FlingPaths.h
  FlingEngine/Resources/src/FlingAssetPaths.cpp.in
  FlingEngine/Utils/src/Timing.cpp
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/src/SandboxGame.cpp
  imgui.ini
Labels: PRI 2, enhancement

#127 Cubemap reflections
  Assets/Shaders/CubeMapReflections.frag
  Assets/Shaders/CubeMapReflections.vert
  Assets/Shaders/CubeMapReflections_frag.spv
  Assets/Shaders/CubeMapReflections_vert.spv
  Assets/Shaders/PBRDefault.frag
  Assets/Textures/Skybox/Garden/negx.jpg
  Assets/Textures/Skybox/Garden/negy.jpg
  Assets/Textures/Skybox/Garden/negz.jpg
  Assets/Textures/Skybox/Garden/posx.jpg
  Assets/Textures/Skybox/Garden/posy.jpg
  Assets/Textures/Skybox/Garden/posz.jpg
  Assets/Textures/Skybox/Garden/readme.txt
  FlingEngine/Editor/src/BaseEditor.cpp
  FlingEngine/Graphics/inc/Cubemap.h
  FlingEngine/Graphics/inc/DesktopWindow.h
  FlingEngine/Graphics/inc/FlingImgui.h
  FlingEngine/Graphics/inc/MeshRenderer.h
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/inc/ShaderPrograms/ShaderProgramManager.h
  FlingEngine/Graphics/inc/ShaderPrograms/ShaderProgramReflections.h
  FlingEngine/Graphics/src/Cubemap.cpp
  FlingEngine/Graphics/src/FlingImgui.cpp
  FlingEngine/Graphics/src/MeshRenderer.cpp
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Graphics/src/ShaderPrograms/ShaderProgramManager.cpp
  FlingEngine/Graphics/src/ShaderPrograms/ShaderProgramReflections.cpp
  FlingEngine/Resources/inc/HDRImage.h
  FlingEngine/Resources/inc/Image.h
  FlingEngine/Resources/src/HDRImage.cpp
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: PRI 2, enhancement
