Repository flingengine/FlingEngine, pull requests merged in 2019-10, with the labels that each got.

#74 Staging branch added
  README.md
Labels: enhancement

#76 Change the max number of Dynamic UBO matrices created to support the…
  FlingEngine/Graphics/inc/Renderer.h
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: bug fix

#86 Cubemaps
  Assets/Shaders/skybox/skybox.frag
  Assets/Shaders/skybox/skybox.frag.spv
  Assets/Shaders/skybox/skybox.vert
  Assets/Shaders/skybox/skybox.vert.spv
  Assets/Textures/Skybox/negx.jpg
  Assets/Textures/Skybox/negy.jpg
  Assets/Textures/Skybox/negz.jpg
  Assets/Textures/Skybox/posx.jpg
  Assets/Textures/Skybox/posy.jpg
  Assets/Textures/Skybox/posz.jpg
  Assets/Textures/Skybox/readme.txt
  FlingEngine/Graphics/inc/Buffer.h
  FlingEngine/Graphics/inc/Cubemap.h
  FlingEngine/Graphics/inc/GraphicsHelpers.h
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/inc/UniformBufferObject.h
  FlingEngine/Graphics/src/Cubemap.cpp
  FlingEngine/Graphics/src/FlingImgui.cpp
  FlingEngine/Graphics/src/GraphicsHelpers.cpp
  FlingEngine/Graphics/src/Model.cpp
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Resources/inc/Image.h
  FlingEngine/Resources/src/Image.cpp
Labels: PRI 2, enhancement

#87 Shader reflection for descriptors and Materials
  .travis.yml
  Assets/Levels/Level_1.json
  Assets/Materials/Default.mat
  Assets/Materials/Wood.mat
  Assets/Shaders/shader.vert
  Assets/Shaders/vert.spv
  Assets/Textures/DefaultTexture.png
  CMake/FlingEngineInc.cmake
  CMakeLists.txt
  Config/EngineConf.ini
  FlingEngine/CMakeLists.txt
  FlingEngine/Core/inc/Engine.h
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Gameplay/inc/Components/Transform.h
  FlingEngine/Gameplay/src/Components/Transform.cpp
  FlingEngine/Graphics/inc/Buffer.h
  FlingEngine/Graphics/inc/FlingVulkan.h
  FlingEngine/Graphics/inc/GraphicsHelpers.h
  FlingEngine/Graphics/inc/ImguiDisplay.h
  FlingEngine/Graphics/inc/Material.h
  FlingEngine/Graphics/inc/MeshRenderer.h
  FlingEngine/Graphics/inc/PhyscialDevice.h
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/inc/Sampler.hpp
  FlingEngine/Graphics/inc/Shader.h
  FlingEngine/Graphics/inc/ShaderProgram.h
  FlingEngine/Graphics/inc/UniformBufferObject.h
  FlingEngine/Graphics/src/Buffer.cpp
  FlingEngine/Graphics/src/GraphicsHelpers.cpp
  FlingEngine/Graphics/src/ImguiDisplay.cpp
  FlingEngine/Graphics/src/Instance.cpp
  FlingEngine/Graphics/src/Material.cpp
  FlingEngine/Graphics/src/MeshRenderer.cpp
  FlingEngine/Graphics/src/Model.cpp
  FlingEngine/Graphics/src/PhyscialDevice.cpp
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Graphics/src/Sampler.cpp
  FlingEngine/Graphics/src/Shader.cpp
  FlingEngine/Graphics/src/ShaderProgram.cpp
  FlingEngine/Platform/inc/PlatformLinux.h
  FlingEngine/Platform/inc/PlatformWindows.h
  FlingEngine/Resources/inc/Image.h
  FlingEngine/Resources/inc/JsonFile.h
  FlingEngine/Resources/src/Image.cpp
  FlingEngine/Utils/inc/FlingTypes.h
  FlingEngine/Utils/inc/Memory.h
  FlingEngine/Utils/inc/MovingAverage.hpp
  FlingEngine/Utils/inc/Stats.h
  FlingEngine/Utils/inc/Timing.h
  FlingEngine/Utils/src/Stats.cpp
  FlingEngine/Utils/src/Timing.cpp
  Sandbox/CMakeLists.txt
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/inc/SandboxUI.h
  Sandbox/Gameplay/src/SandboxGame.cpp
  Sandbox/Gameplay/src/SandboxUI.cpp
  Sandbox/main.cpp
Labels: PRI 0, enhancement

#93 Use a ciruclar buffer for our descriptor set binding pools
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Utils/inc/CircularBuffer.hpp
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: bug fix

#102 Linux render fix
  Assets/Levels/Level_1.json
  Assets/Shaders/PBRDefault.frag
  Assets/Shaders/PBRDefault.vert
  Assets/Shaders/PBRDefault_frag.spv
  Assets/Shaders/PBRDefault_vert.spv
  Config/EngineConf.ini
  FlingEngine/Graphics/inc/Lighting/DirectionalLight.hpp
  FlingEngine/Graphics/inc/Lighting/PointLight.hpp
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/src/Renderer.cpp
  Sandbox/Gameplay/inc/Mover.h
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: PRI 0, bug fix
