Repository flingengine/FlingEngine, pull requests merged in 2019-09, with the labels that each got.

#36 Cleanup the World to not be a singleton, and give each level an ownin…
  FlingEngine/Core/inc/Engine.h
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Gameplay/inc/Level.h
  FlingEngine/Gameplay/inc/World.h
  FlingEngine/Gameplay/src/Level.cpp
  FlingEngine/Gameplay/src/World.cpp
Labels: PRI 2, enhancement

#39 Added getting mouse position functions to input
  FlingEngine/Core/inc/Input/Input.h
  FlingEngine/Core/inc/Input/LinuxInput.h
  FlingEngine/Core/inc/Input/WindowsInput.h
  FlingEngine/Core/src/Input/LinuxInput.cpp
  FlingEngine/Core/src/Input/WindowsInput.cpp
Labels: PRI 2, enhancement

#49 Remove python using of sys in the shader compiler
  Assets/Shaders/compileShaders.py
Labels: PRI 3, enhancement

#48 Add a Depth Buffer to Vulkan and add 3D support
  Assets/Shaders/shader.vert
  Assets/Shaders/vert.spv
  FlingEngine/Graphics/inc/DepthBuffer.h
  FlingEngine/Graphics/inc/GraphicsHelpers.h
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/inc/Vertex.h
  FlingEngine/Graphics/src/DepthBuffer.cpp
  FlingEngine/Graphics/src/GraphicsHelpers.cpp
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Platform/inc/PlatformLinux.h
  FlingEngine/Platform/inc/PlatformWindows.h
  FlingEngine/Resources/inc/Image.h
  FlingEngine/Resources/src/Image.cpp
  FlingEngine/Utils/inc/Logger.h
Labels: enhancement

#56 Gcc warning cleanup and remove component manager
  CMakeLists.txt
  FlingEngine/Core/inc/ComponentManager.h
  FlingEngine/Core/inc/Engine.h
  FlingEngine/Core/src/ComponentManager.cpp
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Graphics/src/DepthBuffer.cpp
  FlingEngine/Graphics/src/PhyscialDevice.cpp
  FlingEngine/Resources/src/Image.cpp
  FlingEngine/Utils/inc/pch.h
Labels: bug, enhancement

#60 Made a vector of models to be loaded and remove un-used functions
  FlingEngine/Graphics/inc/Renderer.h
  FlingEngine/Graphics/src/Renderer.cpp
Labels: PRI 2, enhancement

#61 Basic Gameplay Layer
  FlingEngine/Core/inc/Engine.h
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Gameplay/inc/Game.h
  FlingEngine/Gameplay/inc/World.h
  FlingEngine/Gameplay/src/World.cpp
  FlingEngine/Graphics/inc/FlingVulkan.h
  FlingEngine/Utils/inc/Logger.h
  Sandbox/CMakeLists.txt
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/src/SandboxGame.cpp
  Sandbox/main.cpp
Labels: PRI 0, enhancement

#67 fixed gimbal lock
  Config/EngineConf.ini
  FlingEngine/Core/inc/FlingMath.h
  FlingEngine/Core/inc/Input/LinuxInput.h
  FlingEngine/Core/inc/Input/WindowsInput.h
  FlingEngine/Core/src/Input/LinuxInput.cpp
  FlingEngine/Core/src/Input/WindowsInput.cpp
  FlingEngine/Gameplay/inc/FirstPersonCamera.h
  FlingEngine/Gameplay/src/FirstPersonCamera.cpp
  FlingEngine/Graphics/src/Renderer.cpp
Labels: PRI 0, bug

#69 Add input delegate mappings
  FlingEngine/Core/inc/Input/Input.h
  FlingEngine/Core/inc/Input/Input.inl
  FlingEngine/Core/src/Engine.cpp
  FlingEngine/Core/src/Input/LinuxInput.cpp
  FlingEngine/Core/src/Input/WindowsInput.cpp
  FlingEngine/Gameplay/inc/World.h
  FlingEngine/Graphics/src/Renderer.cpp
  FlingEngine/Utils/inc/pch.h
  README.md
  Sandbox/Gameplay/inc/SandboxGame.h
  Sandbox/Gameplay/src/SandboxGame.cpp
Labels: enhancement
